#! /bin/sh

if [ $# != 1 ]
then
    echo "usage: newboard boardname"
    exit 1
fi

from=/home/pace/pace-kicad
bname=$1

if [ ! -r .git ]
then
    git init
fi

if [ -r ${bname} ]
then
    echo "error: kicad subdirectory ${bname} already exists"
    exit 1
fi


mkdir ${bname}
cp $from/jlc/fp-lib-table ${bname}/
cp $from/jlc/sym-lib-table ${bname}/
cp $from/jlc/jlc.pro ${bname}/$bname.pro
cp $from/jlc/jlc.sch ${bname}/$bname.sch
cp $from/jlc/jlc.kicad_pcb ${bname}/$bname.kicad_pcb
cp $from/Makefile.board ${bname}/Makefile

cat $from/ignore >> .gitignore
cat $from/.gitattributes >> .gitattributes

git config filter.kicad_project.clean "sed 's/^update=.*/update=Date/'"
git config filter.kicad_project.smudge cat

git config filter.kicad_sch.clean "sed -E 's/(#PWR|FLG)[0-9]+/\1?/'"
git config filter.kicad_sch.smudget cat

